<?php
// user \dclass\devups\model\Model;

class ImageCore extends Model implements JsonSerializable
{

    /**
     * @Id @GeneratedValue @Column(type="integer")
     * @var int
     * */
    protected $id;
    /**
     * @Column(name="reference", type="string" , length=123  , nullable=true)
     * @var string
     **/
    protected $reference;
    /**
     * @Column(name="name", type="string" , length=123 , nullable=true )
     * @var string
     **/
    protected $name;
    /**
     * @Column(name="description", type="text"  , nullable=true)
     * @var text
     **/
    protected $description;
    /**
     * @Column(name="image", type="string" , length=255 )
     * @var string
     **/
    protected $image;
    /**
     * @Column(name="uploaddir", type="string" , length=255 )
     * @var string
     **/
    protected $uploaddir;
    /**
     * @Column(name="size", type="float"  , nullable=true)
     * @var float
     **/
    protected $size;
    /**
     * @Column(name="width", type="float"  , nullable=true)
     * @var float
     **/
    protected $width;
    /**
     * @Column(name="height", type="float"  , nullable=true)
     * @var float
     **/
    protected $height;


    public function __construct($id = null)
    {

        if ($id) {
            $this->id = $id;
        }

    }

    public function getId()
    {
        return $this->id;
    }

    public function getReference()
    {
        return $this->reference;
    }

    public function setReference($reference)
    {
        $this->reference = $reference;
    }

    public function getName()
    {
        return $this->name;
    }

    public function setName($name)
    {
        $this->name = $name;
    }

    public function getDescription()
    {
        return $this->description;
    }

    public function setDescription($description)
    {
        $this->description = $description;
    }

    /**
     * @return string
     */
    public function getUploaddir(): string
    {
        return $this->uploaddir;
    }

    /**
     * @param string $uploaddir
     */
    public function setUploaddir(string $uploaddir): void
    {
        $this->uploaddir = $uploaddir;
    }

    public function uploadImage($file = 'image')
    {
        $dfile = self::Dfile($file);
        if (!$dfile->errornofile) {

            $url = $dfile
                ->hashname()
                ->moveto($this->uploaddir);

            if (!$url['success']) {
                return array('success' => false,
                    'error' => $url);
            }

            $this->image = $url['file']['hashname'];
        }
    }

    public function srcImage($prefix = "")
    {
        return Dfile::show($prefix . $this->image, $this->uploaddir);
    }

    public function showImage()
    {
        $url = Dfile::show($this->image, $this->uploaddir);
        return Dfile::fileadapter($url, $this->image);
    }

    public function getImage()
    {
        return $this->image;
    }

    public function setImage($image)
    {
        $this->image = $image;
    }

    public function getSize()
    {
        return $this->size;
    }

    public function setSize($size)
    {
        $this->size = $size;
    }

    public function getWidth()
    {
        return $this->width;
    }

    public function setWidth($width)
    {
        $this->width = $width;
    }

    public function getHeight()
    {
        return $this->height;
    }

    public function setHeight($height)
    {
        $this->height = $height;
    }


    public function jsonSerialize()
    {
        return [
            'id' => $this->id,
            'reference' => $this->reference,
            'name' => $this->name,
            'description' => $this->description,
            'image' => $this->image,
            'size' => $this->size,
            'width' => $this->width,
            'height' => $this->height,
        ];
    }

    public function __insert()
    {
        if(!$this->image || !$this->uploaddir)
            return 0;

        return parent::__insert(); // TODO: Change the autogenerated stub
    }

    public function __update($arrayvalues = null, $seton = null, $case = null, $defauljoin = true)
    {
        if(!$this->image || !$this->uploaddir)
            return 0;

        return parent::__update($arrayvalues, $seton, $case, $defauljoin); // TODO: Change the autogenerated stub
    }

}
