<?php


namespace dclass\devups;
use Request as R;

class Api extends \Response
{
    public static $params = [];
    public static $pm_items = [];
    private $_name = "";
    public $method = "";
    public $header = [];
    /**
     * @param $url
     * @param $callback
     * @return Api
     */
    public static function post($url, $callback){
        $api = new Api();
        $api->name($url);
        $api->method = "post";

        //$urlvar = explode("/:", $url);
        if(R::get('path') == $url){
            $callbackarray = explode(".", $callback);
            $data = call_user_func($callbackarray[0], $callbackarray[1]);

        }
        return $api;
    }

    public function name($name){
        $this->_name = $name;
    }

    public function param(... $param){

    }

    public function row(){

    }

    public function formData(){

    }

    public function run($options = 0, $depth = 512, $argv = null)
    {
        if ($argv) {
            self::$pm_items[] = [

            ];
            return null;
        }

        parent::json_response($options, $depth); // TODO: Change the autogenerated stub
    }

    public static function toPostManDoc(){
        $postmandoccontent = <<<EOF
{
	"info": {
		"_postman_id": "00de1303-c785-4215-84ed-0c1719fc8426",
		"name": "mobstores",
		"schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
	},
	"item": [
		{
			"name": "Module Customer",
			"item": [
				{
					"name": "add customer",
					"request": {
						"method": "POST",
						"header": [
							{
								"key": "x-access-token",
								"value": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJucGF0cmljaWFAYW9sLmNvbSIsImlhdCI6MTU0NjQ5NTc5N30.ptj_dx1no_2-Tzqmvj6C5P_v3jNrVnJU5NOpC8byjIo",
								"type": "text"
							},
							{
								"key": "Content-Type",
								"name": "Content-Type",
								"value": "application/json",
								"type": "text"
							}
						],
						"body": {
							"mode": "raw",
							"raw": "[{\r\n\"id_commerce\": \"commerce_ms000010\",\r\n\"loan\":[{\r\n\"date_update_payment\":\"2018-04-29T12:15:14.841Z\",\r\n\"date_relance\":\"2018-04-29T12:15:14.841Z\",\r\n\"loan_amount\":5000,\r\n\"id_sale\": \"vente_commerce_ms00001_82abf80c-0d99-462d-9aad-9f3fbc69229a\"\r\n}],\r\n\"document\":\"client\",\r\n\"name\":\"djougue\",\r\n\"first_name\":\"donald\",\r\n\"mobile_banking_number\":\"679494639\",\r\n\"account_number\":\"32255455222\",\r\n\"email\":\"djouguae@gmail.com\",\r\n\"pwd\":\"donald11123\",\r\n\"address\":\"rond point damas\",\r\n\"phone_numbers\":[\"679494639\",\"690069916\"],\r\n\"num_cni\":\"g23451151n\",\r\n\"image\":\"https://commerceMobile.com/images/damarus_00001.png\"\r\n}]\r\n"
						},
						"url": {
							"raw": "http://163.172.25.183:3000/commerce/commerce_ms00001/customer/",
							"protocol": "http",
							"host": [
								"163",
								"172",
								"25",
								"183"
							],
							"port": "3000",
							"path": [
								"commerce",
								"commerce_ms00001",
								"customer",
								""
							]
						}
					},
					"response": []
				},
				{
					"name": "get customer",
					"request": {
						"method": "GET",
						"header": [
							{
								"key": "x-access-token",
								"value": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJucGF0cmljaWFAYW9sLmNvbSIsImlhdCI6MTU0NjQ5NTc5N30.ptj_dx1no_2-Tzqmvj6C5P_v3jNrVnJU5NOpC8byjIo",
								"type": "text"
							},
							{
								"key": "Content-Type",
								"value": "application/json",
								"type": "text"
							}
						],
						"url": {
							"raw": "http://163.172.25.183:3000/commerce/commerce_ms00016/customer",
							"protocol": "http",
							"host": [
								"163",
								"172",
								"25",
								"183"
							],
							"port": "3000",
							"path": [
								"commerce",
								"commerce_ms00016",
								"customer"
							]
						}
					},
					"response": []
				},
				{
					"name": "GET CLIENTS FOR COMMERCE",
					"request": {
						"method": "GET",
						"header": [
							{
								"key": "x-access-token",
								"value": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJucGF0cmljaWFAYW9sLmNvbSIsImlhdCI6MTU0NjQ5NTc5N30.ptj_dx1no_2-Tzqmvj6C5P_v3jNrVnJU5NOpC8byjIo",
								"type": "text"
							},
							{
								"key": "Content-Type",
								"value": "application/json",
								"type": "text"
							}
						],
						"url": {
							"raw": "http://163.172.25.183:3000/commerce/commerce_ms00001/customer/",
							"protocol": "http",
							"host": [
								"163",
								"172",
								"25",
								"183"
							],
							"port": "3000",
							"path": [
								"commerce",
								"commerce_ms00001",
								"customer",
								""
							]
						}
					},
					"response": []
				},
				{
					"name": "UPDATE CLIENT",
					"request": {
						"method": "PUT",
						"header": [
							{
								"key": "x-access-token",
								"value": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJucGF0cmljaWFAYW9sLmNvbSIsImlhdCI6MTU0NjQ5NTc5N30.ptj_dx1no_2-Tzqmvj6C5P_v3jNrVnJU5NOpC8byjIo",
								"type": "text"
							},
							{
								"key": "Content-Type",
								"value": "application/json",
								"type": "text"
							}
						],
						"body": {
							"mode": "raw",
							"raw": "{\n    \"account_number\": \"32255455222\",\n    \"address\": \"nouvelle route bastos\",\n    \"date_creation\": \"2019-01-02T20:40:55Z\",\n    \"document\": \"client\",\n    \"email\": \"djouguae@gmail.com\",\n    \"first_name\": \"donald basso\",\n    \"id_client\": \"client_commerce_ms00001_1b73a167-2640-44aa-a236-62a1ed34322a\",\n    \"id_commerce\": \"commerce_ms00001\",\n    \"image\": \"https://commerceMobile.com/images/damarus_00001.png\",\n    \"loan\": [\n        {\n            \"date_relance\": \"2018-04-29T12:15:14.841Z\",\n            \"date_update_payment\": \"2018-04-29T12:15:14.841Z\",\n            \"id_sale\": \"vente_commerce_ms00001_82abf80c-0d99-462d-9aad-9f3fbc69229a\",\n            \"loan_amount\": 5000\n        }\n    ],\n    \"mobile_banking_number\": \"679494639\",\n    \"name\": \"djougue\",\n    \"num_cni\": \"g23451151n\",\n    \"phone_numbers\": [\n        \"679494639\",\n        \"690069916\"\n    ],\n    \"pwd\": \"donald11123\"\n}"
						},
						"url": {
							"raw": "http://163.172.25.183:3000/commerce/commerce_ms00001/customer/client_commerce_ms00001_1b73a167-2640-44aa-a236-62a1ed34322a",
							"protocol": "http",
							"host": [
								"163",
								"172",
								"25",
								"183"
							],
							"port": "3000",
							"path": [
								"commerce",
								"commerce_ms00001",
								"customer",
								"client_commerce_ms00001_1b73a167-2640-44aa-a236-62a1ed34322a"
							]
						}
					},
					"response": []
				},
				{
					"name": "GET ALL CUSTOMER TRANSCATION",
					"request": {
						"method": "GET",
						"header": [
							{
								"key": "x-access-token",
								"value": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJucGF0cmljaWFAYW9sLmNvbSIsImlhdCI6MTU0NjQ5NTc5N30.ptj_dx1no_2-Tzqmvj6C5P_v3jNrVnJU5NOpC8byjIo",
								"type": "text"
							},
							{
								"key": "Content-Type",
								"value": "application/json",
								"type": "text"
							}
						],
						"url": {
							"raw": "http://163.172.25.183:3000/commerce/commerce_ms00018/customer/client_commerce_ms00018_7cc5eb57-f9f5-4600-939d-f324d176f8ec/transaction/all",
							"protocol": "http",
							"host": [
								"163",
								"172",
								"25",
								"183"
							],
							"port": "3000",
							"path": [
								"commerce",
								"commerce_ms00018",
								"customer",
								"client_commerce_ms00018_7cc5eb57-f9f5-4600-939d-f324d176f8ec",
								"transaction",
								"all"
							]
						}
					},
					"response": []
				},
				{
					"name": "GET CUSTOMER TRANSCATION FOR A SPECIFIC PERIOD USING PAGING",
					"request": {
						"method": "GET",
						"header": [
							{
								"key": "x-access-token",
								"value": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJucGF0cmljaWFAYW9sLmNvbSIsImlhdCI6MTU0NjQ5NTc5N30.ptj_dx1no_2-Tzqmvj6C5P_v3jNrVnJU5NOpC8byjIo",
								"type": "text"
							},
							{
								"key": "Content-Type",
								"value": "application/json",
								"type": "text"
							}
						],
						"url": {
							"raw": "http://163.172.25.183:3000/commerce/commerce_ms00018/customer/client_commerce_ms00018_7cc5eb57-f9f5-4600-939d-f324d176f8ec/transaction/period/2019-04-10/2019-12-12/paging/0/1000",
							"protocol": "http",
							"host": [
								"163",
								"172",
								"25",
								"183"
							],
							"port": "3000",
							"path": [
								"commerce",
								"commerce_ms00018",
								"customer",
								"client_commerce_ms00018_7cc5eb57-f9f5-4600-939d-f324d176f8ec",
								"transaction",
								"period",
								"2019-04-10",
								"2019-12-12",
								"paging",
								"0",
								"1000"
							]
						},
						"description": "starting_date =2019-04-10\r\nend_date = 2019-12-12\r\noffset = 0\r\nlimit= 1000\r\n"
					},
					"response": []
				},
				{
					"name": "GET CUSTOMER TRANSCATIONS",
					"request": {
						"method": "GET",
						"header": [
							{
								"key": "x-access-token",
								"value": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJucGF0cmljaWFAYW9sLmNvbSIsImlhdCI6MTU0NjQ5NTc5N30.ptj_dx1no_2-Tzqmvj6C5P_v3jNrVnJU5NOpC8byjIo",
								"type": "text"
							},
							{
								"key": "Content-Type",
								"value": "application/json",
								"type": "text"
							}
						],
						"url": {
							"raw": "http://163.172.25.183:3000/commerce/commerce_ms00018/customer/client_commerce_ms00018_7cc5eb57-f9f5-4600-939d-f324d176f8ec/transaction/all",
							"protocol": "http",
							"host": [
								"163",
								"172",
								"25",
								"183"
							],
							"port": "3000",
							"path": [
								"commerce",
								"commerce_ms00018",
								"customer",
								"client_commerce_ms00018_7cc5eb57-f9f5-4600-939d-f324d176f8ec",
								"transaction",
								"all"
							]
						}
					},
					"response": []
				},
				{
					"name": "GET CLIENT SOLDE FOR COMMERCE",
					"request": {
						"method": "GET",
						"header": [
							{
								"key": "x-access-token",
								"value": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJucGF0cmljaWFAYW9sLmNvbSIsImlhdCI6MTU0NjQ5NTc5N30.ptj_dx1no_2-Tzqmvj6C5P_v3jNrVnJU5NOpC8byjIo",
								"type": "text"
							},
							{
								"key": "Content-Type",
								"value": "application/json",
								"type": "text"
							}
						],
						"url": {
							"raw": "http://163.172.25.183:3000/commerce/commerce_ms00018/customer/solde/all",
							"protocol": "http",
							"host": [
								"163",
								"172",
								"25",
								"183"
							],
							"port": "3000",
							"path": [
								"commerce",
								"commerce_ms00018",
								"customer",
								"solde",
								"all"
							]
						}
					},
					"response": []
				},
				{
					"name": "DELETE CLIENT",
					"request": {
						"method": "DELETE",
						"header": [
							{
								"key": "x-access-token",
								"value": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJucGF0cmljaWFAYW9sLmNvbSIsImlhdCI6MTU0NjQ5NTc5N30.ptj_dx1no_2-Tzqmvj6C5P_v3jNrVnJU5NOpC8byjIo",
								"type": "text"
							},
							{
								"key": "Content-Type",
								"value": "application/json",
								"type": "text"
							}
						],
						"url": {
							"raw": "http://163.172.25.183:3000/commerce/commerce_ms00001/customer/client_commerce_ms00001_1b73a167-2640-44aa-a236-62a1ed34322a",
							"protocol": "http",
							"host": [
								"163",
								"172",
								"25",
								"183"
							],
							"port": "3000",
							"path": [
								"commerce",
								"commerce_ms00001",
								"customer",
								"client_commerce_ms00001_1b73a167-2640-44aa-a236-62a1ed34322a"
							]
						}
					},
					"response": []
				}
			]
		}
    }
]	
EOF;

    }
}