     ALTER TABLE local_content DROP FOREIGN KEY FK_63103524D211F64E;
     ALTER TABLE local_content ADD CONSTRAINT FK_63103524D211F64E FOREIGN KEY (local_content_key_id) REFERENCES local_content_key (id) ON DELETE SET NULL;
     ALTER TABLE page_local_content DROP FOREIGN KEY FK_F2CA451FE683F9BD;
     ALTER TABLE page_local_content DROP FOREIGN KEY FK_F2CA451FF7563416;
     ALTER TABLE page_local_content ADD CONSTRAINT FK_F2CA451FE683F9BD FOREIGN KEY (local_content_id) REFERENCES local_content (id) ON DELETE SET NULL;
     ALTER TABLE page_local_content ADD CONSTRAINT FK_F2CA451FF7563416 FOREIGN KEY (page_mapped_id) REFERENCES page_mapped (id) ON DELETE SET NULL;
