     ALTER TABLE product ADD status_id INT DEFAULT NULL;
     ALTER TABLE product ADD CONSTRAINT FK_D34A04AD6BF700BD FOREIGN KEY (status_id) REFERENCES tree_item (id) ON DELETE SET NULL;
     CREATE INDEX IDX_D34A04AD6BF700BD ON product (status_id);
