/**
 * slideCtrl
 * Generated by devups
 * on 2021/01/30
 */


$('#dv_table tbody').sortable({
    helper: fixWidthHelper,
    stop: function (event, ui) {
        var i = 0;
        var datapersit = [];
        for (var item of $(this).find("tr")) {
            i++;
            $(item).find(".position").html(i);
        }

    }
}).disableSelection();

function fixWidthHelper(e, ui) {
    ui.children().each(function () {
        $(this).width($(this).width());
    });
    return ui;
}

model.init("slide");
model.slide = {
    changeStatus: function (el, id) {
        model.request("slide.change-status&id=" + id)
            .toFormdata({"activate": $(el).find("input").val()})
            .post(function (response) {

                $.notify("List Réorganisée!", "success");
            });
    },
    sortlist: function (el) {
        model.addLoader($(el))
        var fd = new FormData();
        $.each($('#dv_table tbody').find('tr'), function (i, tr) {
            console.log(tr);
            fd.append("positions[]", $(tr).attr("id"));
        });
        model.request("slide.orderlist").data(fd).post((response) => {
            model.removeLoader();
            console.log(response);
            // ddatatable._reload();
            $.notify("List Réorganisée!", "success");
        });

    }
};
