/**
 * reportingmodelForm
 * Generated by devups
 * on 2021/04/05
 */

var reportingmodel = {
    delay: null,
    lang: "fr",
    template: $("#template").html(),
    editorlangs: {},
    editor: {},
    previewFrame: {},
    preview: {},
    init() {
        $(".dv-editable").hide()
        $("#container-" + this.lang).show()

        let previewFrame = document.getElementById('preview');
        this.preview = previewFrame.contentDocument || previewFrame.contentWindow.document;

        for (let lang of langs) {
            this.editorlangs[lang.iso_code] = CodeMirror.fromTextArea(document.getElementById('code-' + lang.iso_code), {
                mode: 'text/html'
            })
            this.editorlangs[lang.iso_code].on("change", () => {
                clearTimeout(this.delay);
                this.delay = setTimeout(() => this.updatePreview(), 300);
            });
        }
        this.editor = this.editorlangs[this.lang];
        this.updatePreview()

    },
    updatePreview() {

        this.preview.open();
        this.preview.write(
            this.template.replace(/{yield}/g, this.editor.getValue().replace(/{__env}/g, __env))
        );
        this.preview.close();
        $(this.preview.getElementsByTagName("body")).attr("contenteditable", true)
        // added this line

    },
    updateEditor() {
        this.editor.setValue($(this.preview.getElementById("yield")).html())
    },
    loadFromFile(el, lang) {
        model.addLoader($(el))
        Drequest.init(__env + "admin/api/reportingmodel.load-content?lang="+lang+"&name=" + report.name)
            .get((response) => {
                model.removeLoader()
                if (response.success)
                    this.editor.setValue(response.content)
                else {
                    alert(response.detail)
                }
            })
    },
    submit(el) {

        // var form = $("#cmstext-form");
        var fd = new FormData();
        for (let lang of langs) {
            fd.append("reportingmodel_form[content][" + lang.iso_code + "]", this.editorlangs[lang.iso_code].getValue())
            fd.append("reportingmodel_form[contenttext][" + lang.iso_code + "]", $("#contenttext-" + lang.iso_code).val())
        }
        model.addLoader($(el))

        Drequest.init(__env + "api/update.reportingmodel?id=" + report.id)
            .data(fd)
            .post((response) => {
                console.log(response);
                model.removeLoader()
                $.notify("Modification enregistrées", "info")
            })
    },
    changelang(el) {
        $(".dv-editable").hide()
        $("#container-" + el.value).show()
        // $(".dv-title").hide()
        // $("#dv-title-" + el.value).show()

        this.lang = el.value;

        this.editor = this.editorlangs[this.lang];
        this.updatePreview()
        console.log(this.editor)
        // let previewFrame = document.getElementById('preview');
        // this.preview = previewFrame.contentDocument || previewFrame.contentWindow.document;

    },

}
reportingmodel.init();