/**
 * dv_imageCtrl
 * Generated by devups
 * on 2021/01/18
 */

ddatatable.addrow = function (tablerow) {
    //this.dtinstance.find("#dv_table").find("tbody").prepend(tablerow);
    $("#dv_dv_image_table").find(".row").prepend(tablerow);
}
ddatatable.callbackpaginaison = function (response) {
    $("#dv_dv_image_table").find(".row").html(response.datatable.tablebody);
    $("#dv_pagination").replaceWith(response.datatable.tablepagination);
}

console.log("dsfdf");
var droppedFiles = false;
var $form = $("#galleryContainer");
$form.addClass('has-advanced-upload');
$form.on('drag dragstart dragend dragover dragenter dragleave drop', function (e) {
    e.preventDefault();
    e.stopPropagation();
})
    .on('dragover dragenter', function () {
        $form.addClass('is-dragover');
    })
    .on('dragleave dragend drop', function () {
        $form.removeClass('is-dragover');
    })
    .on('drop', function (e) {
        droppedFiles = e.originalEvent.dataTransfer.files;


        model.init("dv_image");
        //ddatatable.init("dv_image");
        var param = ddatatable.dtinstance.find("#dv_table").data('filterparam');
        console.log(param)
        console.log(droppedFiles)
        for (var i = 0; i < droppedFiles.length; i++) {
            var file = droppedFiles[i];
            console.log(file)
            var fd = new FormData();
            fd.append("image", file);
            fd.append("name", file.name);

            $.notify("Uploading "+file.name, "info")
            // Drequest.init($("#dv_table").data("route") + "services.php?path=chapter.scanpages" + param)
            model.request("dv_image.store" + param)
                .data(fd)
                .post(function (response) {
                    console.log(response);
                    if(response.success){

                        ddatatable.addrow(response.tablerow);
                        $.notify("Upload complete of "+file.name, "success");
                        return ;
                    }
                    // todo handle error message of upload image
                });

        }
    });


model.dvimage = {
    _delete: function (el, id) {
        model._delete(el, id, "dv_image",(response) => {
            $("#image-" + id).remove();
        })
    },
    _edit: function (id) {
        model._edit(id, "dv_image")
    },
    setcover(el, idchap, idimage) {
        model.addLoader($(el));
        model.request("chapter.setcover")
            .param({"id": idchap, "idscan": idimage})
            .get((response) => {
                console.log(response);
                $(".widget-content").removeClass("cover")
                $("#image-" + idimage).find(".widget-content").addClass("cover")
                model.removeLoader();
                $.notify("Cover updated!", "success");
            })

    },
    sortlist: function (el) {
        model.addLoader($(el))
        var fd = new FormData();
        $.each($('.image-items').find('.image-item'), function (i, tr) {
            fd.append("positions[]", $(tr).attr("id").replace('image-', ""));
        });

        model.request("scanpage.sort")
            .data(fd)
            .post((response) => {
                console.log(response);
                model.removeLoader();
                $.notify("List Réorganisée!", "success");
            })
        // model._post("status.orderlist", fd, function (response) {
        //     model.removeLoader();
        //     console.log(response);
        //     // ddatatable._reload();
        //     $.notify("List Réorganisée!", "success");
        // });

    }
};
