/**
* dv_imageCtrl
* Generated by devups
* on 2021/01/18
*/

ddatatable.addrow = function (tablerow) {
    //this.dtinstance.find("#dv_table").find("tbody").prepend(tablerow);
    $("#dv_dv_image_table").find(".row").prepend(tablerow);
}